#!/usr/bin/env python3
"""Exact-build, single-country-overlay experiment; no firmware/IPCC downloads."""
import argparse
import asyncio
import fcntl
import json
import os
from pathlib import Path
import plistlib
import posixpath
import secrets
import subprocess

import carrier
import catalog
import transport_canary as transport

PARENT = '/var/mobile/Library/CountryBundles/Overlay'
LEAF = 'device+carrier+com.apple.Belarus+V54+72.7.1.plist'
TARGET = PARENT + '/' + LEAF
ORIGINAL = '5c6260617f3e1cb1016d185e0a6c875f041495d041a8b227d3450b01e808df80'
CANDIDATE = 'b4f26cb87a2be2d58551740acce54fd9d0b473ca653a2fef98e285f8a557fb4d'


def transform(value, mode, original_backup=None):
    digest = carrier.digest(value)
    carrier.require(digest in (ORIGINAL, CANDIDATE), 'Неизвестный страновой файл; запись запрещена')
    carrier.require(mode in ('apply', 'inspect', 'restore'), 'Unknown mode')
    if mode == 'inspect': return value
    wanted = CANDIDATE if mode == 'apply' else ORIGINAL
    if digest == wanted: return value
    if mode == 'restore':
        carrier.require(original_backup is not None and carrier.digest(original_backup) == ORIGINAL,
                        'Для возврата нужны точные исходные байты из private этого устройства')
        return original_backup
    data = plistlib.loads(value)
    data['Show5GSwitch'] = mode == 'apply'
    result = plistlib.dumps(data, fmt=plistlib.FMT_BINARY, sort_keys=False)
    carrier.require(carrier.digest(result) == wanted, 'Generated bytes differ from tested file')
    return result


def check_report(report):
    carrier.require(all(report.get(k) == v for k, v in transport.EXPECTED.items()),
                    'Только iPhone18,2 / iOS 27.2 / 24B5084k')
    expected = {('257', '01', 'com.apple.mobilkom_by', '72.7.1'),
                ('257', '04', 'com.apple.life_by', '72.7')}
    actual = [(c.get('MCC'), c.get('MNC'), c.get('CFBundleIdentifier'), c.get('CFBundleVersion'))
              for c in report['carriers']]
    carrier.require(len(actual) == 2 and set(actual) == expected
                    and report.get('SIMStatus') == 'kCTSIMSupportSIMStatusReady',
                    'Нужны готовые штатные A1 72.7.1 и life 72.7; прежний CarrierLab автоматически не удаляется')


def new_session(module, serial, profile, mode):
    token = secrets.token_hex(10)
    directory = catalog.PRIVATE / ('country-' + token)
    directory.mkdir(mode=0o700)
    state = dict(device=serial, profile=profile, target=TARGET, token=token,
                 source='airlift-src-' + token, link='airlift-link-' + token,
                 exported='airlift-recovered-' + token, phase='created', mode=mode)
    catalog.store(directory/'state.json', state)
    return CountrySession(module, serial, directory, state)


class CountrySession(catalog.Session):
    async def read_file(self, afc):
        path = self.state['exported']
        meta = await catalog.info(afc, path)
        carrier.require(meta and meta.get('st_ifmt') == 'S_IFREG'
                        and 0 < int(meta['st_size']) <= 65536, 'Unexpected exported object')
        first = await afc.get_file_contents(path)
        carrier.require(first == await afc.get_file_contents(path), 'Unstable country file')
        return first

    async def perform(self, afc, mode):
        s, d = self.state, self.directory
        original = None
        await self.backup_books(afc)
        pairs = [('../../'+s['source']+'/p0/p1/p2/link', s['link']),
                 (posixpath.relpath(TARGET, catalog.AIRLOCK), s['exported']),
                 ('../../'+s['exported'], s['link']+'/'+LEAF)]
        catalog.durable_bytes(d/'payload.zip', self.module.build_archive(PARENT, b'unused'))
        catalog.durable_bytes(d/'Books.plist', self.module.build_books([p[0] for p in pairs]))
        self.phase('stage_intent')
        try:
            await self.native('stage', s['source'], s['link'], s['exported'],
                              d/'payload.zip', d/'Books.plist', d/'books-native')
            self.phase('export_intent')
            await self.export_paused(pairs)
            await self.await_export(afc, True)
            self.phase('exported')
            original = await self.read_file(afc)
            catalog.durable_bytes(d/'original.plist', original)
            self.phase('backup_verified', original_sha256=carrier.digest(original))
            candidate = transform(original, mode, getattr(self, 'restore_bytes', None))
            catalog.durable_bytes(d/'desired.plist', candidate)
            self.phase('write_intent', desired_sha256=carrier.digest(candidate))
            if original != candidate:
                await afc.set_file_contents(s['exported'], candidate)
            carrier.require(await self.read_file(afc) == candidate, 'Country write readback failed')
            self.phase('write_verified')
            await self.return_directory(afc)
            await self.cleanup(afc)
            return candidate
        except BaseException:
            # Return original in the still-paused session whenever possible.
            # Unknown/interrupted returns remain blocked with backups preserved.
            if self.worker is not None and self.worker.returncode is None:
                if await catalog.info(afc, s['exported']) is not None:
                    if original is not None:
                        await afc.set_file_contents(s['exported'], original)
                        carrier.require(await self.read_file(afc) == original, 'Original restoration failed')
                    await self.return_directory(afc)
                    await self.cleanup(afc)
            raise


def pending():
    transport.require_completed_canaries(catalog.PRIVATE)
    for pattern in ('country-*/state.json', 'catalog-*/state.json', 'install-*/state.json'):
        for p in catalog.PRIVATE.glob(pattern):
            state = json.loads(p.read_text())
            carrier.require(state.get('phase') == 'complete',
                            'Незавершённая операция: '+str(p.parent)+'. Сохраните private; повторная запись заблокирована.')


async def execute(mode):
    from pymobiledevice3.lockdown import create_using_usbmux
    from pymobiledevice3.services.afc import AfcService
    report = await carrier.doctor()
    check_report(report)
    serial, profile = await transport.identify()
    module = transport.load_transport()
    session = new_session(module, serial, profile, mode)
    if mode == 'restore':
        for saved in sorted(catalog.PRIVATE.glob('country-*/state.json'), key=lambda p:p.stat().st_mtime, reverse=True):
            state = json.loads(saved.read_text())
            backup = saved.parent/'original.plist'
            if state.get('device') == serial and state.get('target') == TARGET and backup.is_file():
                value = backup.read_bytes()
                if carrier.digest(value) == ORIGINAL:
                    session.restore_bytes = value
                    break
    print('Резервная копия: '+str(session.directory), flush=True)
    async with await create_using_usbmux(serial=serial, autopair=False, connection_type='USB') as dev:
        async with AfcService(dev) as afc:
            desired = await session.perform(afc, mode)
            if mode != 'inspect':
                session.phase('verification_pending')
                proof = new_session(module, serial, profile, 'inspect')
                observed = await proof.perform(afc, 'inspect')
                carrier.require(observed == desired, 'iOS изменила файл после записи; результат не подтверждён')
                session.phase('complete', verified_by=proof.directory.name)
    after = await carrier.doctor()
    carrier.require(after == report, 'Метаданные SIM изменились; проверьте связь')
    result = dict(phase='complete', mode=mode, Show5GSwitch=plistlib.loads(desired)['Show5GSwitch'],
                  network_5g_verified=False, reboot_verified=False,
                  before=report, after=after, **{'run':str(session.directory)})
    catalog.store(session.directory/'result.json', result)
    print(json.dumps(result, ensure_ascii=False), flush=True)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--yes', action='store_true')
    p.add_argument('--inspect', action='store_true', help='Export/return without content edits; not read-only')
    p.add_argument('--restore', action='store_true', help='Restore known original country bytes')
    a = p.parse_args(argv)
    carrier.require(not (a.inspect and a.restore), 'Choose inspect or restore')
    os.umask(0o077)
    catalog.PRIVATE.mkdir(exist_ok=True)
    check_report(asyncio.run(carrier.doctor()))
    print('Эксперимент для этой сборки: только страновой Show5GSwitch.\nВременный перенос файла и данных Books; резервная копия в private.\nCarrierLab, Docomo и прошивка не скачиваются. Оба оператора используют этот страновой файл.', flush=True)
    if not a.yes and input('Продолжить? Введите ДА: ').strip() != 'ДА': return 0
    with (catalog.PRIVATE/'device-operation.lock').open('a') as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX|fcntl.LOCK_NB)
        pending()
        subprocess.run(['make','-C',str(catalog.ROOT/'vendor/airlift')], check=True,
                       stdout=subprocess.DEVNULL)
        asyncio.run(execute('inspect' if a.inspect else 'restore' if a.restore else 'apply'))
    if not a.inspect and not a.restore:
        print('Запись проверена. Перезагрузите iPhone вручную. Проверьте меню, интернет и звонки.\nПосле разблокировки: zsh Start.command --inspect\nВозврат исходного файла: zsh Start.command --restore')
    return 0


if __name__ == '__main__':
    try: raise SystemExit(main())
    except Exception as e:
        print('Остановлено: '+str(e)); raise SystemExit(2)
